### ISSUE TITLE
Read from linDB

### ISSUE THREAD

**Issue by SerjZimmer** [lindb/client_go#6]
Hello, I am studying the linDB database, and I understand how to write data, but unfortunately there is no example of reading data from the database, can you tell me something? Interested in Golang.

**Comment by stone1100** [comment]
Currently, reading data through the client is not supported.
LinDB provides a Restful API, data and status can be read through HTTP.

Ref:
- https://lindb.io/api/lin-ql.html#execute-linql
- https://lindb.io/guide/lin-ql.html

A version can be released this week to support reading data and status through the client.

**Comment by stone1100** [comment]
@SerjZimmer v0.0.2, reading metric data and metadata is supported.

example: https://github.com/lindb/client_go/blob/main/example/read_data.go

**Comment by SerjZimmer** [comment]
Great, thank you ! Could you add more early examples of linQL?

**Comment by stone1100** [comment]
> Great, thank you ! Could you add more early examples of linQL?

Ref: https://lindb.io/guide/lin-ql.html#metric-query

**Comment by SerjZimmer** [comment]
I mean the need in my case to write down the data for the past week. For example. I make a request for certain metrics from 2023.04.04 to 2023.04.11 and the result is that there is no data in this time interval. So, can I add randomly generated data to this interval?

**Comment by stone1100** [comment]
You can specify the time range that can be written in the new database(https://lindb.io/guide/lin-ql.html#create-database), and the data within this time range can be written.
Can set timestamp of data point(https://github.com/lindb/client_go/blob/main/api/point.go#L59).

For example:
database config: behead => 7d , ahead => 1h , data can be written in (now-7d ~ now+1h)

**Comment by SerjZimmer** [comment]
Thank you so much!

**Comment by SerjZimmer** [comment]
where should i put the new date?

	for unix := 1680742861; unix < 1681261261; unix += 10 {
		// cpu params
		CpuS := CpuParams()

		// write cpu data
		uT := int64(unix)
		date := time.Unix(uT, 0)

		point := api.Point{}
		point.SetTimestamp(date)

		wc.AddPoint(context.TODO(), api.NewPoint("cpu").
			AddTag("host", "host1").
			AddField(api.NewLast("free", CpuS.free)).
			AddField(api.NewLast("usage", CpuS.usedPer)).
			AddField(api.NewLast("core1", CpuS.core1)).
			AddField(api.NewLast("core2", CpuS.core2)).
			AddField(api.NewLast("core3", CpuS.core3)).
			AddField(api.NewLast("core4", CpuS.core4)).
			AddField(api.NewLast("core5", CpuS.core5)).
			AddField(api.NewLast("core6", CpuS.core6)).
			AddField(api.NewLast("core7", CpuS.core7)).
			AddField(api.NewLast("core8", CpuS.core8)).
			AddField(api.NewLast("MHz", CpuS.usedMHz)))
	}

**Comment by stone1100** [comment]
```go
	for unix := 1680742861; unix < 1681261261; unix += 10 {
		// cpu params
		CpuS := CpuParams()

		// write cpu data
		uT := int64(unix)
		date := time.Unix(uT, 0)

		wc.AddPoint(context.TODO(), api.NewPoint("cpu").
			SetTimestamp(date).  // <= set timestamp
			AddTag("host", "host1").
			AddField(api.NewLast("free", CpuS.free)).
			AddField(api.NewLast("usage", CpuS.usedPer)).
			AddField(api.NewLast("core1", CpuS.core1)).
			AddField(api.NewLast("core2", CpuS.core2)).
			AddField(api.NewLast("core3", CpuS.core3)).
			AddField(api.NewLast("core4", CpuS.core4)).
			AddField(api.NewLast("core5", CpuS.core5)).
			AddField(api.NewLast("core6", CpuS.core6)).
			AddField(api.NewLast("core7", CpuS.core7)).
			AddField(api.NewLast("core8", CpuS.core8)).
			AddField(api.NewLast("MHz", CpuS.usedMHz)))
	}
```

**Comment by SerjZimmer** [comment]
You my best friend!!!!!))))))
